### ISSUE TITLE
Do you need to rebuild dependency packages on deploy?

### ISSUE THREAD

**Issue by shawnmclean** [tommedema/serverless-mono-example#5]
Lets say you update something in a dependency package (`random`), but in your sls project you run the deploy/build, it will not pull in that change because main is pointing to `dist/index.js`.

Is there a way to point directly to the ts file so no build is required?

**Comment by justinwaite** [comment]
In my experience, building and deploying from the sls project will rebuild `random`, as long as it is a dependency. That's part of the typescript 3 project references I think.

Do you have your tsconfig file for the sls project referencing `random` properly?

**Comment by tommedema** [comment]
When you run `serverless deploy` this starter will automatically rebuild due to this line:

https://github.com/tommedema/serverless-mono-example/blob/master/packages/sls-random/serverless.yml#L34

**Comment by shawnmclean** [comment]
Thanks both. I tried the ts 3 references feature, I checked out this project along with a few others and it didn't seem to build the dependencies.

When using `sls`, it runs that custom script that explicitly runs the yarn build. That works but not the one that uses tsc.
