### ISSUE TITLE
Cannot find module '@org/random'

### ISSUE THREAD

**Issue by jesuspc** [tommedema/serverless-mono-example#8]
After just cloning and yarn installing, and without building the project both of my editors (VSCode and emacs with tide) report "Cannot find module '@org/random'". Weirdly, if I run tsc --traceResolution inside sls-random I get:

> Module name '@org/random' was successfully resolved to '/Users/prietoj/Code/serverless-mono-example/packages/random/src/index.ts'.

Can this be related to the issue being tracked in https://github.com/tommedema/serverless-mono-example/issues/4?

**Comment by tommedema** [comment]
Yes, this is indeed the same issue as described in #4. It depends on https://github.com/Microsoft/TypeScript/issues/26913
