### ISSUE TITLE
GraphQL Integration

### ISSUE THREAD

**Issue by emptyway** [tommedema/serverless-mono-example#9]
how would you integrate AWS Appsync or Apollo GraphQL with this mono-repo architecture?

**Comment by tommedema** [comment]
I haven't tried this myself, but it would be part of any of the individual packages. Having a mono-repo architecture shouldn't affect the way you work with these libraries?

**Comment by emptyway** [comment]
thank you for your response. can you create a service without a `package.json`

I want to create a service/package AppSync; referencing and mapping others packages with no lambda functions in it. 

Similarly, how would you create a package/service/resource Cognito User Pool, S3 bucket, Database or any resources without any lambda functions in it. 

whats your recommendation?  thanks!

**Comment by emptyway** [comment]
worked with the a minimal `package.json`, `serverless.yml` and `tsconfig.json`
